name: Daily Commit
on:
  schedule:
    - cron: '00 0 * * *'  # Fixed cron syntax (removed extra space)
  workflow_dispatch:  # Allows manual trigger
jobs:
  update-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch full history for proper merging
      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
      - name: Pull latest changes
        run: |
          git pull origin main --rebase || echo "No need to pull"  # Changed 'master' to 'main'
      - name: Make changes
        run: |
          echo "Daily commit on $(date)" >> daily_commit.txt
      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Daily commit on $(date)" || echo "No changes to commit"
          git push origin main
      - name: Step by 23f2003751@ds.study.iitm.ac.in  # Modified to include email in step name
        run: echo "Commit made by GitHub Actions"
